// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleSearchService.Infrastructure.Persistence;

#nullable disable

namespace VehicleSearchService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VssDbContext))]
    partial class VssDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("VehicleSearchService.Infrastructure.Persistence.Entities.LocationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("VehicleSearchService.Infrastructure.Persistence.Entities.ReservationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("PickupAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("PickupLocationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ReturnAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ReturnLocationId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("reservations", (string)null);
                });

            modelBuilder.Entity("VehicleSearchService.Infrastructure.Persistence.Entities.VehicleMarketRecord", b =>
                {
                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)");

                    b.Property<string>("MarketCode")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("VehicleId", "MarketCode");

                    b.ToTable("vehicle_markets", (string)null);
                });

            modelBuilder.Entity("VehicleSearchService.Infrastructure.Persistence.Entities.VehicleRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VehicleTypeCatalogId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("VehicleSearchService.Infrastructure.Persistence.Entities.VehicleMarketRecord", b =>
                {
                    b.HasOne("VehicleSearchService.Infrastructure.Persistence.Entities.VehicleRecord", "Vehicle")
                        .WithMany("EnabledMarkets")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleSearchService.Infrastructure.Persistence.Entities.VehicleRecord", b =>
                {
                    b.HasOne("VehicleSearchService.Infrastructure.Persistence.Entities.LocationRecord", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("VehicleSearchService.Infrastructure.Persistence.Entities.VehicleRecord", b =>
                {
                    b.Navigation("EnabledMarkets");
                });
#pragma warning restore 612, 618
        }
    }
}
